#!/bin/bash
set -e

cd $(dirname $0)/..

apt-get update
apt-get install -y arptables python-pip python-dev rsync

pip install --upgrade pip tox virtualenv

# Switch to pip installed pip...
/usr/local/bin/pip install psutil
/usr/local/bin/pip install subprocess32


if [ ! -x "$(which nsenter)" ]; then
    TMP=$(mktemp -d)
    trap "rm -rf $TMP" exit

    cd $TMP
    wget https://github.com/rancherio/agent-binaries/releases/download/v0.1.2/agent-binaries.tar.gz
    tar xzf agent-binaries.tar.gz
    find -type f -name nsenter -exec cp -v {} /usr/local/bin/nsenter \;
    chmod +x /usr/local/bin/nsenter
fi
