#!/bin/bash
set -e

cd $(dirname $0)/..

apt-get update
apt-get install -y arptables rsync libssl-dev libffi-dev uuid-runtime

if [ ! -e /opt/python/2.7.11 ]; then

    mkdir -p /opt/python/2.7.11
    curl https://www.python.org/ftp/python/2.7.11/Python-2.7.11.tgz | tar -zxv -C /tmp/

    pushd /tmp/Python-2.7.11/
    ./configure --prefix=/opt/python/2.7.11
    make
    make install

    popd
fi
curl https://bootstrap.pypa.io/get-pip.py | /opt/python/2.7.11/bin/python
/opt/python/2.7.11/bin/pip install tox psutil subprocess32 ndg-httpsclient

if [ ! -x "$(which nsenter)" ]; then
    TMP=$(mktemp -d)
    trap "rm -rf $TMP" exit

    cd $TMP
    wget https://github.com/rancherio/agent-binaries/releases/download/v0.1.2/agent-binaries.tar.gz
    tar xzf agent-binaries.tar.gz
    find -type f -name nsenter -exec cp -v {} /usr/local/bin/nsenter \;
    chmod +x /usr/local/bin/nsenter
fi
