#!/bin/bash
set -e

python_deps()
{
    if diff -q requirements.txt dist/requirements.txt >/dev/null 2>&1; then
        return 0
    fi

    VER=$(pip --version | awk '{print $2}')
    MAJOR=$(echo $VER | cut -f1 -d.)
    MINOR=$(echo $VER | cut -f2 -d.)
    if [ "$MAJOR" -lt 2 ] && [ "$MINOR" -lt 5 ]
    then
        echo "[ERROR] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" 1>&2
        echo "[ERROR] !! pip 1.5 or newer is required !!" 1>&2
        echo "[ERROR] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" 1>&2
        exit 1
    fi

    if [ -e dist ]; then
        rm -rf dist
    fi

    for req in $(grep -iv "websockify\|psutil\|subprocess32\|ndg-httpsclient" < requirements.txt); do
        pip install -t dist $req
    done
    cp requirements.txt dist
}

cd $(dirname $0)/..

python_deps

if [ -e build ]; then
    rm -rf build
fi
