#!/bin/bash
set -e

cd $(dirname $0)/..

if [ -x "$(which wrapdocker)" ]; then
    wrapdocker > /tmp/docker.log 2>&1
    docker ps
fi

find -depth -name '*.pyc' -o -name '__pycache__' -exec rm -rf {} \;
mkdir -p /var/lib/cattle

TMP=$(mktemp -d --tmpdir=/scratch)

trap "rm -rf $TMP" exit

rsync -a ./ $TMP
pushd $TMP

sudo env DOCKER_TEST=true tox -e flake8
sudo env DOCKER_TEST=true tox -e py27

popd
rsync -a --delete $TMP/.tox/ .tox
