#!/bin/bash
set -x -e

cd $(dirname $0)/..

if [ -x "$(which wrapdocker)" ]; then
    wrapdocker
    LANG=C.UTF-8 LANGUAGE=C /etc/init.d/libvirt-bin start
    docker ps
fi

find -depth -name '*.pyc' -o -name '__pycache__' -exec rm -rf {} \;
mkdir -p /var/lib/cattle

TMP=$(mktemp -d --tmpdir=/scratch)

trap "rm -rf $TMP" exit

rsync -a ./ $TMP
pushd $TMP

sudo env LIBVIRT_TEST=true DOCKER_TEST=true tox

popd
rsync -a --delete $TMP/.tox/ .tox
